'use client';

import { useState } from 'react';
import { ArrowRight, Clock, Mail, MapPin, MessageSquare, Phone, Send } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const inquiryTypes = ['General Information', 'Registration Application', 'Licence Renewal', 'Continuing Education', 'Committee Information', 'Complaint or Disciplinary Matter', 'Nursing Agency Licensing', 'Document Verification', 'Website Technical Support', 'Other'];

const contactMethods = [
  { icon: Phone, title: 'Call us', details: ['(242) 604-6015', '(242) 604-6017'], description: 'Speak with our team during office hours.', available: 'Mon–Fri: 9:00am–5:00pm', href: 'tel:+12426046015' },
  { icon: Mail, title: 'Email us', details: ['info@nursingcouncilbahamas.com'], description: 'Send a detailed enquiry to our team.', available: 'Response within 24 hours', href: 'mailto:info@nursingcouncilbahamas.com' },
  { icon: MapPin, title: 'Visit us', details: ['Virginia & Augusta Streets', 'Nassau, Bahamas'], description: 'Visit our office for in-person assistance.', available: 'Mon–Fri: 9:00am–5:00pm', href: '#office-location' },
];

const departmentContacts = [
  { department: 'Registration Services', email: 'registration@nursingcouncilbahamas.com', phone: '(242) 604-6015 ext. 101', description: 'New registrations, renewals, and licence verifications' },
  { department: 'Education & Continuing Education', email: 'education@nursingcouncilbahamas.com', phone: '(242) 604-6015 ext. 102', description: 'CE requirements, approved programs, and educational standards' },
  { department: 'Committees & Governance', email: 'committees@nursingcouncilbahamas.com', phone: '(242) 604-6015 ext. 103', description: 'Committee information and meeting schedules' },
  { department: 'Nursing Agency Licensing', email: 'agencies@nursingcouncilbahamas.com', phone: '(242) 604-6015 ext. 104', description: 'Agency licensing, compliance, and regulations' },
];

const faqs = [
  { question: 'How long does the registration process take?', answer: 'The nursing registration process typically takes 4–6 weeks from submission of a complete application with all required documents.' },
  { question: 'When is the deadline for licence renewal?', answer: 'All nursing licences must be renewed by December 31st each year. Late renewals incur additional fees.' },
  { question: 'How many continuing education units do I need?', answer: 'Registered nurses must complete 24 continuing education units annually to maintain their licence.' },
  { question: 'Can I verify a nurse’s registration online?', answer: 'Yes, you can verify current nursing registrations using the online search tool on the homepage.' },
];

export default function ContactPage() {
  const [formData, setFormData] = useState({ name: '', email: '', phone: '', inquiryType: '', subject: '', message: '' });
  const handleInputChange = (field: string, value: string) => setFormData((previous) => ({ ...previous, [field]: value }));
  const handleSubmit = (event: React.FormEvent) => { event.preventDefault(); console.log('Form submitted:', formData); };

  return (
    <>
      <Header />
      <main className="flex-1">
        <section className="bg-council-primary py-20 text-white lg:py-28">
          <div className="container mx-auto grid gap-10 px-4 lg:grid-cols-[1.1fr_0.9fr] lg:items-end">
            <div><p className="mb-5 flex items-center gap-3 text-sm font-semibold uppercase tracking-[0.16em] text-council-accent"><span className="h-px w-10 bg-council-accent" />We are here to help</p><h1 className="font-heading mb-6 text-5xl font-bold leading-tight md:text-6xl">Contact & Help</h1><p className="max-w-2xl text-xl leading-relaxed text-white/85">Get in touch for support with registration, licensing, or questions about nursing regulation in The Bahamas.</p></div>
            <div className="border-l-4 border-council-accent bg-white/10 p-7"><p className="mb-3 text-sm font-semibold uppercase tracking-[0.14em] text-council-accent">Office hours</p><p className="font-heading text-3xl font-bold">Monday–Friday</p><p className="mt-1 text-xl text-white/85">9:00am–5:00pm</p><a href="tel:+12426046015" className="mt-6 inline-flex items-center gap-2 font-semibold text-white hover:text-council-accent"><Phone className="h-4 w-4" /> (242) 604-6015</a></div>
          </div>
        </section>

        <section className="relative z-10 -mt-10 pb-20"><div className="container mx-auto px-4"><div className="grid gap-px bg-slate-200 shadow-xl md:grid-cols-3">{contactMethods.map((method) => { const Icon = method.icon; return <a key={method.title} href={method.href} className="group bg-white p-7 transition-colors hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-council-primary"><div className="mb-8 flex items-start justify-between"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-council-primary text-white"><Icon className="h-6 w-6" /></div><ArrowRight className="h-5 w-5 text-council-primary transition-transform group-hover:translate-x-1" /></div><h2 className="font-heading mb-4 text-2xl font-bold text-council-dark">{method.title}</h2><div className="mb-3 space-y-1 font-semibold text-council-primary">{method.details.map((detail) => <p key={detail}>{detail}</p>)}</div><p className="mb-5 text-sm leading-relaxed text-gray-600">{method.description}</p><p className="flex items-center gap-2 text-sm text-gray-500"><Clock className="h-4 w-4" />{method.available}</p></a>; })}</div></div></section>

        <section className="bg-white pb-20 lg:pb-28"><div className="container mx-auto grid max-w-7xl gap-12 px-4 lg:grid-cols-[1.08fr_0.92fr]">
          <div><p className="mb-4 flex items-center gap-3 text-sm font-semibold uppercase tracking-[0.16em] text-council-primary"><span className="h-px w-9 bg-council-accent" />Send a message</p><h2 className="font-heading mb-7 text-4xl font-bold text-council-dark">How can we help?</h2><form onSubmit={handleSubmit} className="border border-slate-200 bg-white p-6 shadow-sm md:p-8"><div className="grid gap-5 md:grid-cols-2"><label className="text-sm font-medium text-gray-700">Full name *<Input required value={formData.name} onChange={(event) => handleInputChange('name', event.target.value)} placeholder="Enter your full name" className="mt-2 min-h-12" /></label><label className="text-sm font-medium text-gray-700">Email address *<Input type="email" required value={formData.email} onChange={(event) => handleInputChange('email', event.target.value)} placeholder="Enter your email address" className="mt-2 min-h-12" /></label><label className="text-sm font-medium text-gray-700">Phone number<Input type="tel" value={formData.phone} onChange={(event) => handleInputChange('phone', event.target.value)} placeholder="(242) xxx-xxxx" className="mt-2 min-h-12" /></label><label className="text-sm font-medium text-gray-700">Inquiry type *<Select onValueChange={(value) => handleInputChange('inquiryType', value)}><SelectTrigger className="mt-2 min-h-12"><SelectValue placeholder="Select inquiry type" /></SelectTrigger><SelectContent>{inquiryTypes.map((type) => <SelectItem key={type} value={type.toLowerCase().replace(/\s+/g, '-')}>{type}</SelectItem>)}</SelectContent></Select></label></div><label className="mt-5 block text-sm font-medium text-gray-700">Subject *<Input required value={formData.subject} onChange={(event) => handleInputChange('subject', event.target.value)} placeholder="Brief description of your enquiry" className="mt-2 min-h-12" /></label><label className="mt-5 block text-sm font-medium text-gray-700">Message *<Textarea required rows={6} value={formData.message} onChange={(event) => handleInputChange('message', event.target.value)} placeholder="Please provide details about your enquiry..." className="mt-2 resize-none" /></label><Button type="submit" className="mt-6 min-h-14 w-full bg-council-primary text-base hover:bg-council-secondary"><Send className="h-5 w-5" />Send message</Button><p className="mt-4 text-center text-sm text-gray-500">We typically respond to enquiries within 24 hours during business days.</p></form></div>
          <div id="office-location" className="scroll-mt-8"><p className="mb-4 flex items-center gap-3 text-sm font-semibold uppercase tracking-[0.16em] text-council-primary"><span className="h-px w-9 bg-council-accent" />Visit our office</p><h2 className="font-heading mb-7 text-4xl font-bold text-council-dark">Our location</h2><div className="overflow-hidden bg-gray-200" style={{ height: '300px' }}><iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3604.456!2d-77.356!3d25.08!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x892f7c99b66b7e23%3A0x8e7b8f0c8e7b8f0c!2sVirginia%20St%20%26%20Augusta%20St%2C%20Nassau%2C%20Bahamas!5e0!3m2!1sen!2sus!4v1643723400000" width="100%" height="100%" style={{ border: 0 }} allowFullScreen loading="lazy" referrerPolicy="no-referrer-when-downgrade" title="Nursing Council of the Bahamas Location" /></div><div className="bg-council-primary p-7 text-white md:p-8"><MapPin className="mb-5 h-8 w-8 text-council-accent" /><div className="grid gap-6 sm:grid-cols-2"><div><h3 className="mb-2 font-semibold text-council-accent">Address</h3><p className="leading-relaxed text-white/85">Virginia & Augusta Streets<br />Nassau, Bahamas</p></div><div><h3 className="mb-2 font-semibold text-council-accent">Office hours</h3><p className="leading-relaxed text-white/85">Monday–Friday: 9:00am–5:00pm<br />Saturday–Sunday: Closed</p></div><div><h3 className="mb-2 font-semibold text-council-accent">Public holidays</h3><p className="leading-relaxed text-white/85">Closed on all Bahamian public holidays.</p></div><div><h3 className="mb-2 font-semibold text-council-accent">Parking</h3><p className="leading-relaxed text-white/85">Limited street parking and public parking nearby.</p></div></div></div></div>
        </div></section>

        <section className="bg-gray-50 py-20 lg:py-28"><div className="container mx-auto px-4"><div className="mb-12 grid gap-6 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><div><p className="mb-4 flex items-center gap-3 text-sm font-semibold uppercase tracking-[0.16em] text-council-primary"><span className="h-px w-9 bg-council-accent" />Direct support</p><h2 className="font-heading text-4xl font-bold text-council-dark md:text-5xl">Department contacts</h2></div><p className="max-w-2xl text-lg leading-relaxed text-gray-600">Contact a specialist team directly for more focused support and faster service.</p></div><div className="mx-auto grid max-w-6xl gap-px border border-slate-200 bg-slate-200 md:grid-cols-2">{departmentContacts.map((department, index) => <article key={department.department} className="bg-white p-7 md:p-8"><span className="mb-8 block text-sm font-bold text-council-primary">0{index + 1}</span><h3 className="font-heading mb-3 text-2xl font-bold text-council-dark">{department.department}</h3><p className="mb-6 leading-relaxed text-gray-600">{department.description}</p><div className="space-y-3 border-l-2 border-council-accent pl-4 text-sm"><a href={`mailto:${department.email}`} className="flex items-start gap-2 text-council-primary hover:underline"><Mail className="mt-0.5 h-4 w-4 shrink-0" />{department.email}</a><a href={`tel:${department.phone.replace(/[^+\d]/g, '')}`} className="flex items-start gap-2 text-gray-700 hover:text-council-primary"><Phone className="mt-0.5 h-4 w-4 shrink-0" />{department.phone}</a></div></article>)}</div></div></section>

        <section className="bg-white py-20 lg:py-28"><div className="container mx-auto px-4"><div className="mb-12 text-center"><p className="mb-4 flex items-center justify-center gap-3 text-sm font-semibold uppercase tracking-[0.16em] text-council-primary"><span className="h-px w-9 bg-council-accent" />Helpful answers</p><h2 className="font-heading mb-4 text-4xl font-bold text-council-dark">Frequently asked questions</h2><p className="mx-auto max-w-2xl text-lg text-gray-600">Quick answers to common questions. Contact us if you need more detail.</p></div><div className="mx-auto grid max-w-5xl gap-px border border-slate-200 bg-slate-200 md:grid-cols-2">{faqs.map((faq, index) => <article key={faq.question} className="bg-white p-7"><span className="mb-8 block text-sm font-bold text-council-primary">0{index + 1}</span><h3 className="font-heading mb-3 text-xl font-bold text-council-dark">{faq.question}</h3><p className="leading-relaxed text-gray-600">{faq.answer}</p></article>)}</div><div className="mt-12 text-center"><a href="#" onClick={(event) => { event.preventDefault(); window.scrollTo({ top: 0, behavior: 'smooth' }); }} className="inline-flex items-center gap-2 bg-council-primary px-7 py-3 font-semibold text-white transition-colors hover:bg-council-secondary focus:outline-none focus:ring-2 focus:ring-council-primary focus:ring-offset-4"><MessageSquare className="h-5 w-5" />Contact us directly</a></div></div></section>
      </main>
      <Footer />
    </>
  );
}
